name: CI

on:
  push: {}

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-24.04
    permissions: read-all
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      
    - uses: actions/checkout@v4

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=bb --config=rbe_linux_amd64 --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }} //...
        "${GITHUB_WORKSPACE}/bin/bazel" run --config=bb --config=rbe_linux_amd64 --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }} //.github:renovate

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" run --config=bb --config=rbe_linux_amd64 --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }} :mkdocs -- build -d $PWD/site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site/

  build-darwin-aarch64:
    runs-on: macos-14
    permissions: read-all
    steps:
    - uses: actions/checkout@v4

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-darwin-arm64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-darwin-arm64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=bb --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }} //...

  build-windows-x86_64:
    runs-on: windows-2025
    permissions: read-all
    steps:
      - uses: actions/checkout@v4

      - name: Install bazelisk
        run: |
          mkdir $env:GITHUB_WORKSPACE\bin
          Invoke-WebRequest -Uri 'https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-windows-amd64.exe' -OutFile $env:GITHUB_WORKSPACE\bin\bazel.exe

      - name: Test
        run: |
          & "$env:GITHUB_WORKSPACE\bin\bazel.exe" build --config=bb --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_APIKEY }} $(bazel query 'attr("tags", "windows", //...)')

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-24.04
    needs: build-linux-x86_64
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
